version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fukhara
      POSTGRES_DB: fukhara
    ports:
      - 5432:5432
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    environment:
      MOBSF_API_ONLY: 0
      MOBSF_API_KEY: 515d3578262a2539cd13b5b9946fe17e350c321b91faeb1ee56095430242a4a9
    ports:
      - 8181:8000
volumes:
  opensearch_data:

networks:
  fukhara:
    driver: bridge
