version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fukhara
      POSTGRES_PASSWORD: fukhara
    ports:
      - 5432:5432
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fukhara
      MONGO_INITDB_ROOT_PASSWORD: fukhara
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fukhara
      ME_CONFIG_MONGODB_ADMINPASSWORD: fukhara
      ME_CONFIG_BASICAUTH_USERNAME: fukhara
      ME_CONFIG_BASICAUTH_PASSWORD: fukhara
      ME_CONFIG_MONGODB_URL: mongodb://fukhara:fukhara@mongo:27017/
    ports:
      - 8081:8081
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    environment:
      MOBSF_API_ONLY: 0
      MOBSF_API_KEY: 515d3578262a2539cd13b5b9946fe17e350c321b91faeb1ee56095430242a4a9
    ports:
      - 8181:8000
